###GET ACCOUNTS
GET http://localhost:3000/api/v1/accounts

# {"id":3} 

###POST ACCOUNT
POST  http://localhost:3000/api/v1/accounts

{"full_name":"Jorge Rayne David", "email":"jorge@gmail.com", "username":"hello_jorge123", "phone":"12234567890", "password":"helloworld", "shipping_add":"Bulacan", "billing_add": "Bulacan"}

###UPDATE
PUT http://localhost:3000/api/v1/accounts

{"id": 1, "full_name":"Meibelle Medina", "email":"meibelle@gmail.com", "username":"hello_meibelle123", "phone":"12234567890", "password":"hello_world_meibelle", "shipping_add":"Blk2 Lot5 ph2 Lumina Homes Pinagkuartelan Pandi, Bulacan", "billing_add": "Blk2 Lot5 ph2 Lumina Homes Pinagkuartelan Pandi, Bulacan"}

###DELETE
DELETE http://localhost:3000/api/v1/accounts

{"id": 4}