###GET ACCOUNTS
GET http://localhost:3000/api/v1/accounts

# {"id":3} 

###POST ACCOUNT
POST  http://localhost:3000/api/v1/accounts

{"full_name":"Jorge Rayne David", "email":"jorge@gmail.com", "username":"hello_jorge123", "phone":"12234567890", "password":"helloworld", "shipping_add":"Bulacan", "billing_add": "Bulacan"}

###UPDATE
PUT http://localhost:3000/api/v1/accounts

{"id": 1, "full_name":"Meibelle Medina", "email":"meibelle@gmail.com", "username":"hello_meibelle123", "phone":"12234567890", "password":"hello_world_meibelle", "shipping_add":"Blk2 Lot5 ph2 Lumina Homes Pinagkuartelan Pandi, Bulacan", "billing_add": "Blk2 Lot5 ph2 Lumina Homes Pinagkuartelan Pandi, Bulacan"}

###DELETE
DELETE http://localhost:3000/api/v1/accounts

{"id": 4}


###GET CART ITEM
GET http://localhost:3000/api/v1/cart_item

# {"customer_id": 1}

###GET PRODUCTS
GET http://localhost:3000/api/v1/products

###GET ORDERS
GET http://localhost:3000/api/v1/orders

{"id": 3} 


###ADD/POST CART
POST http://localhost:3000/api/v1/cart

{"customer_id":3, "cart_item_id":4, "checkout_num":326}

###ADD/POST PRODUCTS
POST http://localhost:3000/api/v1/products

{"name": "Apple Laptop", "price": 400000, "stocks":5, "seller_id":1}


###EDIT/PUT PRODUCTS
PUT http://localhost:3000/api/v1/products

{"id":1, "name": "Acer Laptop", "price": 40000, "stocks":10}

###DELETE CART_ITEM
DELETE http://localhost:3000/api/v1/cart_item

{"id": 1}

###DELETE PRODUCTS
DELETE http://localhost:3000/api/v1/products

{"id": 4}